### ISSUE TITLE
Not compatible with TODO

### ISSUE THREAD

**Issue by code-tree** [tcarlsen/language-typescript-grammars-only#13]
Atom has a [TODO package](https://github.com/atom/language-todo) that allows styling TODO/NOTE/BUG etc in comments differently to the rest of the comment. I use this a lot to clearly identify TODO items.

![image](https://cloud.githubusercontent.com/assets/11289719/19468536/1105f83c-9541-11e6-8b22-d43a9711ac6e.png)

For some reason this grammar is not compatible with it (ordinary JS package is), but I can't work out why. Could you please fix?

![image](https://cloud.githubusercontent.com/assets/11289719/19468520/f9420fd8-9540-11e6-8687-b339a42aa3f2.png)

thanks

**Comment by tcarlsen** [comment]
please test if this is fixed in 1.6.0

update from #15

**Comment by code-tree** [comment]
Works for me, thanks!
