### ISSUE TITLE
Comments in function parameter lists break syntax highlighting

### ISSUE THREAD

**Issue by pe8ter** [tcarlsen/language-typescript-grammars-only#5]
Placing a `/* ... */` comment in a function parameter list breaks highlighting

Example:

``` typescript
class Foo {
    bar(a: number /* comment */);
    quux(b: number);              // Highlighting is broken.
}
```

Putting the closing parenthesis on a new line fixes the issue, but this is undesirable.

**Comment by tcarlsen** [comment]
fixed in `1.4.0`
